### ISSUE TITLE
CompilerException org.reflections.ReflectionsException: Couldn't find subtypes of Object.

### ISSUE THREAD

**Issue by emil0r** [fn-fx/fn-fx#50] opened 2018-10-30 19:18 UTC
### Steps to Reproduce:
 1. Start an nREPL
 2. Navigate to exampes/getting_started/01_hello_world.clj
 3. Load the entire file

### Expected Result:
Example should be running.

### Actual Result:
Window opens, after that the following stacktrace:

Syntax error compiling at (reflect_utils.clj:36:32).
Couldn't find subtypes of Object. Make sure SubTypesScanner initialized to include Object class - new SubTypesScanner(false)
Oct 30, 2018 8:58:17 PM clojure.tools.logging$eval570$fn__573 invoke
SEVERE: Unhandled REPL handler exception processing message {:op stacktrace, :pprint-fn clojure.pprint/pprint, :print-length 50, :print-level 50, :session 133612c4-ddf3-449d-ba10-65f15bb837d9, :id 13}
java.lang.NullPointerException
	at clojure.string$replace_first.invokeStatic(string.clj:165)
	at clojure.string$replace_first.invoke(string.clj:138)
	at cider.nrepl.middleware.stacktrace$relative_path.invokeStatic(stacktrace.clj:204)
	at cider.nrepl.middleware.stacktrace$relative_path.invoke(stacktrace.clj:198)
	at cider.nrepl.middleware.stacktrace$extract_location.invokeStatic(stacktrace.clj:219)
	at cider.nrepl.middleware.stacktrace$extract_location.invoke(stacktrace.clj:206)
	at clojure.core$comp$fn__5707.invoke(core.clj:2561)
	at clojure.core$map$fn__5766.invoke(core.clj:2747)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:529)
	at clojure.core$seq__5302.invokeStatic(core.clj:137)
	at clojure.core$seq__5302.invoke(core.clj:137)
	at cider.nrepl.middleware.stacktrace$handle_stacktrace.invokeStatic(stacktrace.clj:312)
	at cider.nrepl.middleware.stacktrace$handle_stacktrace.invoke(stacktrace.clj:309)
	at clojure.lang.Var.invoke(Var.java:388)
	at cider.nrepl$wrap_stacktrace$fn__6591.invoke(nrepl.clj:436)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__877.invoke(middleware.clj:22)
	at cider.nrepl$wrap_undef$fn__6623.invoke(nrepl.clj:495)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__877.invoke(middleware.clj:22)
	at refactor_nrepl.middleware$wrap_refactor$fn__6169.invoke(middleware.clj:214)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__877.invoke(middleware.clj:22)
	at cider.nrepl$wrap_classpath$fn__6475.invoke(nrepl.clj:166)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__877.invoke(middleware.clj:22)
	at cider.nrepl$wrap_apropos$fn__6467.invoke(nrepl.clj:158)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__877.invoke(middleware.clj:22)
	at cider.nrepl$wrap_complete$fn__6483.invoke(nrepl.clj:172)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__877.invoke(middleware.clj:22)
	at cider.nrepl$wrap_version$fn__6631.invoke(nrepl.clj:503)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__877.invoke(middleware.clj:22)
	at cider.nrepl$wrap_slurp$fn__6459.invoke(nrepl.clj:150)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__877.invoke(middleware.clj:22)
	at cider.nrepl$wrap_trace$fn__6607.invoke(nrepl.clj:466)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__877.invoke(middleware.clj:22)
	at cider.nrepl$wrap_ns$fn__6543.invoke(nrepl.clj:308)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__877.invoke(middleware.clj:22)
	at cider.nrepl$wrap_info$fn__6517.invoke(nrepl.clj:236)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__877.invoke(middleware.clj:22)
	at cider.nrepl$wrap_profile$fn__6559.invoke(nrepl.clj:345)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__877.invoke(middleware.clj:22)
	at cider.nrepl$wrap_resource$fn__6575.invoke(nrepl.clj:408)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__877.invoke(middleware.clj:22)
	at cider.nrepl$wrap_spec$fn__6583.invoke(nrepl.clj:420)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__877.invoke(middleware.clj:22)
	at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__1160.invoke(interruptible_eval.clj:247)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__877.invoke(middleware.clj:22)
	at cider.nrepl$wrap_inspect$fn__6527.invoke(nrepl.clj:255)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__877.invoke(middleware.clj:22)
	at cider.nrepl$wrap_debug$fn__6493.invoke(nrepl.clj:192)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__877.invoke(middleware.clj:22)
	at cider.nrepl$wrap_enlighten$fn__6501.invoke(nrepl.clj:218)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__877.invoke(middleware.clj:22)
	at clojure.tools.nrepl.middleware.session$add_stdin$fn__1243.invoke(session.clj:238)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__877.invoke(middleware.clj:22)
	at clojure.tools.nrepl.middleware.load_file$wrap_load_file$fn__1286.invoke(load_file.clj:79)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__877.invoke(middleware.clj:22)
	at cider.nrepl$wrap_content_type$fn__6451.invoke(nrepl.clj:139)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__877.invoke(middleware.clj:22)
	at cider.nrepl$wrap_pprint$fn__6441.invoke(nrepl.clj:119)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__877.invoke(middleware.clj:22)
	at cider.nrepl$wrap_refresh$fn__6567.invoke(nrepl.clj:382)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__877.invoke(middleware.clj:22)
	at cider.nrepl$wrap_tracker$fn__6615.invoke(nrepl.clj:484)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__877.invoke(middleware.clj:22)
	at clojure.tools.nrepl.middleware.pr_values$pr_values$fn__1076.invoke(pr_values.clj:22)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__877.invoke(middleware.clj:22)
	at cider.nrepl$wrap_test$fn__6599.invoke(nrepl.clj:446)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__877.invoke(middleware.clj:22)
	at cider.nrepl.middleware.pprint$handle_pprint_fn.invokeStatic(pprint.clj:61)
	at cider.nrepl.middleware.pprint$handle_pprint_fn.invoke(pprint.clj:56)
	at clojure.lang.Var.invoke(Var.java:388)
	at cider.nrepl$wrap_pprint_fn$fn__6431.invoke(nrepl.clj:100)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__877.invoke(middleware.clj:22)
	at cider.nrepl$wrap_out$fn__6551.invoke(nrepl.clj:336)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__877.invoke(middleware.clj:22)
	at clojure.tools.nrepl.middleware.session$session$fn__1228.invoke(session.clj:192)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__877.invoke(middleware.clj:22)
	at clojure.tools.nrepl.server$handle_STAR_.invokeStatic(server.clj:19)
	at clojure.tools.nrepl.server$handle_STAR_.invoke(server.clj:16)
	at clojure.tools.nrepl.server$handle$fn__1301.invoke(server.clj:28)
	at clojure.core$binding_conveyor_fn$fn__5654.invoke(core.clj:2022)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)

### Environment:
- Hash 6edd7a5696246f41d419117e07292a15023fc974 of the project.
- macOS High Sierra
- java 10 2018-03-20
  Java(TM) SE Runtime Environment 18.3 (build 10+46)
  Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)
- Clojure 1.9.0 (also went with a bare bone project with 1.10.0-beta2 and example 2 from getting started, same result)

**Comment by pmonks** [comment] 2018-10-30 20:01
Sadly Oracle has removed the [Oracle Java 10 download](https://www.oracle.com/technetwork/java/javase/downloads/jdk10-downloads-4416644.html) (which appears to be the version you're using), and as best I can tell there's [no OpenJFX release available for OpenJDK v10 (which doesn't bundle JavaFX)](https://openjfx.io/), and I'm unable to reproduce this issue on either Oracle Java 8 (with bundled JavaFX) or Java 11 (using OpenJFX as a dependency).

I realise how big of an ask this is, but are you possibly in a position to upgrade to Java 11, or alternatively perform your fn(fx) development on Java 8?  Those are the last two "Long Term Support" versions of Java, and all earlier "Feature Releases" (Java 9 and Java 10) have been deprecated by Oracle.

As an aside, there's more on Oracle's new (since Java 9) approach to versioning in [this blog post](https://mreinhold.org/blog/forward-faster).

**Comment by pmonks** [comment] 2018-10-30 20:07
Potentially a duplicate of issue #36.

**Closed** 2018-10-31 15:16 UTC
Labels: need info

**Comment by pmonks** [comment] 2018-10-31 18:32
Good to hear!  The library has a few rough edges that we're trying to polish - assistance is very welcome!
